version: '3'
services:
  web:
    image: nginx
    volumes:
      - ./html:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf:/etc/nginx/conf:ro
    ports:
      - "80:80"
    command: [nginx-debug, '-g', 'daemon off;']